-- Using the lazyvim extra for java, that seems to work better

--require('java').setup()
--return {'nvim-java/nvim-java'}
--require('lspconfig').jdtls.setup({})
return {}
--return {
--  "nvim-java/nvim-java",
--  --config = false,
--  dependencies = {
--    {
--      "neovim/nvim-lspconfig",
--      opts = {
--        servers = {
--          -- Your JDTLS configuration goes here
--          jdtls = {
--            settings = {
--              java = {
--                configuration = {
--                  runtimes = {
--                    {
--                      name = "JavaSE-21",
--                      path = "/usr/lib/jvm/temurin-21-jdk-amd64",
--                      default = true,
--                    },
--                  },
--                },
--              },
--            },
--          },
--        },
--        --setup = {
--        --  jdtls = function()
--        --    -- Your nvim-java configuration goes here
--        --    require("java").setup({
--        --      jdtls = {
--        --        version = "v1.44.0",
--        --      },
--        --      lombok = {
--        --        version = "nightly",
--        --      },
--        --      --jdk = {
--        --      --  -- install jdk using mason.nvim
--        --      --  auto_install = true,
--        --      --  version = "21.0.7",
--        --      --},
--        --      -- root_markers = {
--        --      --   "settings.gradle",
--        --      --   "settings.gradle.kts",
--        --      --   "pom.xml",
--        --      --   "build.gradle",
--        --      --   "mvnw",
--        --      --   "gradlew",
--        --      --   "build.gradle",
--        --      --   "build.gradle.kts",
--        --      -- },
--        --    })
--        --  end,
--        --},
--      },
--    },
--  },
--}
